[Interface]
# Home peer: 10.66.66.1/24
PrivateKey = REPLACE_HOME_PRIVATE_KEY
Address = 10.66.66.1/24
Jc = 4
Jmin = 40
Jmax = 70
S1 = 0
S2 = 0
H1 = 1
H2 = 2
H3 = 3
H4 = 4

[Peer]
# Yandex Cloud
PublicKey = REPLACE_YC_PUBLIC_KEY
Endpoint = 158.160.232.44:51821
AllowedIPs = 10.66.66.2/32
PersistentKeepalive = 25
