[Interface]
# YC peer: 10.66.66.2/24
PrivateKey = REPLACE_YC_PRIVATE_KEY
Address = 10.66.66.2/24
ListenPort = 51821
Jc = 4
Jmin = 40
Jmax = 70
S1 = 0
S2 = 0
H1 = 1
H2 = 2
H3 = 3
H4 = 4

[Peer]
# Home MiniPC
PublicKey = REPLACE_HOME_PUBLIC_KEY
AllowedIPs = 10.66.66.1/32
PersistentKeepalive = 25
